### ISSUE TITLE
Text-to-text pipeline (transcript → questions by LLM)

### ISSUE THREAD

**Issue by kjy5** [UWRealityLab/xrcapstone24sp-team2#5]
- Ask LLMs at a fixed time interval (e.g., 30 sec)
- Brainstorm ways to create a list of unique, targeted questions for separate sections of the presentation (prompt engineering is not the focus of this week)

**Comment by junwang0510** [comment]
[PR #13](https://github.com/UWRealityLab/xrcapstone24sp-team2/pull/13)
