### ISSUE TITLE
Create a rubric for grading the presentation

### ISSUE THREAD

**Issue by kjy5** [UWRealityLab/xrcapstone24sp-team2#8]
- Criteria targeting simple movements and speech
- ~4 criteria each, 1-5 scale per criteria (and then scale the summed result to 100)

**Comment by ngand000** [comment]
https://docs.google.com/document/d/1J6Vp79oGcan9AxM4KFQZRUB0aTMOtBON5iowqEAARV8/edit?usp=sharing
